### PR TITLE
Use $DEVKITPPC to locate as and objcopy on Linux

### PR DESCRIPTION
**Pull request by verstatx**
The devkit-env package adds this environment variable to /etc/profile.d/, so we can use it to determine the PATH. Oddly, devkitPPC does not depend on devkit-env. That means it is technically possible to have only one of the two installed, so the redundant check is necessary.

### CODE REVIEW

**Comment by Soapsuds** [comment]
This looks like it would need to be rebased but this would be really nice

**Comment by verstatx** [comment]
Rebased onto latest master. Let me know if any changes need to be made.

**Comment by JLaferri** [comment]
merged, thanks

**Comment by Soapsuds** [comment]
This worked for me! Thanks you two :)

**Pull request merged**
